---

- name: Simple Test
  hosts: "{{ servers }}"
  become: yes
  tasks:
    
  - name: Touch a testfile    
    ansible.builtin.file:
      path: "/home/{{ user_id_personal }}/testfile.txt"
      state: touch
      mode: u=rw,g=r,o=r